FROM registry.access.redhat.com/ubi9/ubi

ARG GRBVER=11.0
ARG GRBFILE=gurobi11.0.0_linux64.tar.gz

USER root
WORKDIR /tmp/

EXPOSE 41954/tcp

RUN curl -O https://packages.gurobi.com/${GRBVER}/${GRBFILE} && \
    tar xf ${GRBFILE} -C /opt && \
    cp /opt/gurobi*/*/bin/{grb_ts,grbgetkey,grbprobe} /usr/local/bin && \
    rm -rf ${GRBFILE} /opt/gurobi*

CMD grbprobe && cat /opt/gurobi/gurobi.lic && grb_ts -v -n
