name: containerfile
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
# Dockerfile.grbts
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.grbts
          tags: rlinfati/containerfile-lab0:grbts-999
# Dockerfile.ikev2-tls
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.ikev2-tls
          tags: rlinfati/containerfile-lab0:ikev2-tls-999
