name: Docker Hub
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.grbts
          tags: rlinfati/containerfile-lab0:grbts-999
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.ikev2-tls
          tags: rlinfati/containerfile-lab0:ikev2-tls-999
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.slurm
          target: slurm-control
          tags: rlinfati/containerfile-lab0:slurm-control-999
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.slurm
          target: slurm-runner
          tags: rlinfati/containerfile-lab0:slurm-runner-999
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.samba
          tags: rlinfati/containerfile-lab0:samba-999
